package com.asledgehammer.webcalc.css.io.token;

public enum CSSTokenType {
  WHITESPACE,
  COMMENT,
  STRING,
  HASH,
  DELIMITER,
  IDENTITY, LEFT_PARENTHESIS, RIGHT_PARENTHESIS, COMMA, COLON, SEMICOLON, AT_KEYWORD, CDO, CDC, NUMERIC, PERCENTAGE, LEFT_SQUAREBRACKET, RIGHT_SQUAREBRACKET, DIMENSION, HEX_COLOR, LEFT_CURLYBRACKET, RIGHT_CURLYBRACKET, GENERIC
}
